language: python

python:
  - 3.8

env:
  - PIPENV_VENV_IN_PROJECT=1
  - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv sync -d
  - cp contib/env-sample .env

script:
  - pipenv run flake8 .
  - pipenv run pytest --cov=ccprod

after_success:
  - pipenv run codecov
