language: python

python:
  - 3.8

services:
  postgresql
addons:
  postgresql: '9.5'

env:
  - PIPENV_VENV_IN_PROJECT=1
  - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv sync -d
  - cp contrib/env-sample .env

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres
script:
  - pipenv run flake8 .
  - pipenv run pytest --cov=ccprod

after_success:
  - pipenv run codecov
